[build-system]
requires = ["setuptools>=65", "wheel", "hatchling"]
build-backend = "setuptools.build_meta"

[project]
name = "fed-yolo"
version = "1.0.1"
description = "Federated Learning Environment Simulation usign flwr and ultralytics"
readme = "README.md"
requires-python = ">=3.12"

authors = [
    {name = "RaghuRam2005", email="atommail20@gmail.com"}
]

dependencies = [
    "flwr[simulation]>=1.27.0",
    "pyyaml>=6.0.3",
    "ultralytics>=8.4.24",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "RaghuRam2005"

[tool.flwr.app.components]
serverapp = "obj_yolo.server:server_app"
clientapp = "obj_yolo.client:client_app"

# Custom config values accessible via `context.run_config`
[tool.flwr.app.config]
num-server-rounds = 20
fraction-train = 1.0
local-epochs = 5
lr0 = 0.001

[tool.setuptools]
packages = ["obj_yolo"]

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 3
options.backend.client-resources.num-cpus = 2
options.backend.client-resources.num-gpus = 1
